parameters:
  cl_tissue.adapter.clamav.class: CL\Tissue\Adapter\ClamAV\ClamAVAdapter
  cl_tissue.adapter.clamavphp.class: CL\Tissue\Adapter\ClamAVPHP\ClamAVPHPAdapter

services:
  cl_tissue.adapter.clamav:
    class: %cl_tissue.adapter.clamav.class%
    arguments:
      - %cl_tissue.adapter.clamav.bin%
      - %cl_tissue.adapter.clamav.database%

  cl_tissue.adapter.clamavphp:
    class: %cl_tissue.adapter.clamavphp.class%
