parameters:
  cl_tissue.adapter_registry.class: CL\Tissue\Adapter\AdapterRegistry

services:
  cl_tissue.adapter_registry:
    class: %cl_tissue.adapter_registry.class%

  cl_tissue.scanner:
    factory_service: cl_tissue.adapter_registry
    factory_method: get
    arguments:
      - %cl_tissue.chosen_adapter_alias%
